const baseURL="/api"
export default{
    USERLOGIN:baseURL+'/userlogin',
    MENULIST:baseURL+'/menulist',
    MENUADD:baseURL+'/menuadd',
    MENUINFO:baseURL+'/menuinfo',
    MENUEDIT:baseURL+'/menuedit',
    MENUDELETE:baseURL+'/menudelete',
    ROLELIST:baseURL+'/rolelist',
    ROLEADD:baseURL+'/roleadd',
    ROLEINFO:baseURL+'/roleinfo',
    ROLEEDIT:baseURL+'/roleedit',
    ROLEDELETE:baseURL+'/roledelete',
    USERLIST:baseURL+'/userlist',
    USERADD:baseURL+'/useradd',
    USERINFO:baseURL+'/userinfo',
    USEREDIT:baseURL+'/useredit',
    USERDELETE:baseURL+'/userdelete',
    USERCOUNT:baseURL+'/usercount',
    CATELIST:baseURL+"/catelist",
    CATEADD:baseURL+"/cateadd",
    CATEINFO:baseURL+"/cateinfo",
    CATEEDIT:baseURL+"/cateedit",
    CATEDELETE:baseURL+"/catedelete",
}